

const Privacy = () => {
    return (
        <div className="max-w-4xl mx-auto py-8 text-gray-300 space-y-16">

            {/* Privacy Policy Section */}
            <section>
                <h1 className="text-4xl font-bold text-white mb-8 border-b border-white/10 pb-4">Privacy Policy</h1>

                <div className="prose prose-invert max-w-none space-y-8">
                    <div className="p-4 bg-cyan-500/10 border border-cyan-500/20 rounded-lg">
                        <p className="text-cyan-300 font-medium m-0">
                            <strong>Core Philosophy: Local Processing First.</strong> <br />
                            We prioritize running AI locally on your device to minimize data exposure. Your sensitive health data is processed with extreme care.
                        </p>
                    </div>

                    <div>
                        <h2 className="text-2xl font-bold text-white mb-4">1. Information We Collect</h2>
                        <ul className="list-disc pl-5 space-y-2">
                            <li><strong>Health & Fitness Data:</strong> We access your step count, heart rate, or sleep data via Apple HealthKit <strong>only with your explicit permission</strong>. This data is used solely to generate AI health insights.</li>
                            <li><strong>AI Conversation History:</strong> To provide a continuous coaching experience, we store your conversation logs locally on your device.</li>
                            <li><strong>Device Information:</strong> We collect necessary device model and OS version details to optimize local Core ML model performance.</li>
                        </ul>
                    </div>

                    <div>
                        <h2 className="text-2xl font-bold text-white mb-4">2. Data Storage & Security</h2>
                        <ul className="list-disc pl-5 space-y-2">
                            <li><strong>Local Processing:</strong> Nucleus prioritizes using local models (like Ollama/Core ML) for data processing. Unless you actively choose to sync or use cloud features, sensitive health analysis is not uploaded to cloud servers.</li>
                            <li><strong>Encryption:</strong> All data stored on your device is protected by iOS system-level encryption.</li>
                            <li><strong>Cloud Minimization:</strong> If you use the Pro features powered by DeepSeek, we practice "Data Minimization" — only the specific metrics needed for your current query are transmitted, and they are not stored for training.</li>
                        </ul>
                    </div>

                    <div>
                        <h2 className="text-2xl font-bold text-white mb-4">3. Third-Party Services</h2>
                        <p>
                            If you use remote AI features (e.g., DeepSeek API), please note that data processing is subject to the respective provider's terms. We ensure that our partners adhere to strict privacy standards.
                        </p>
                    </div>

                    <div>
                        <h2 className="text-2xl font-bold text-white mb-4">4. Your Rights</h2>
                        <ul className="list-disc pl-5 space-y-2">
                            <li>You can withdraw HealthKit authorization at any time in iOS Settings.</li>
                            <li>You can delete all conversation history and analysis data directly within the app.</li>
                        </ul>
                    </div>
                </div>
            </section>

            {/* Terms of Use Section */}
            <section>
                <h1 className="text-4xl font-bold text-white mb-8 border-b border-white/10 pb-4">Terms of Use (EULA)</h1>

                <div className="prose prose-invert max-w-none space-y-8">
                    <div>
                        <h2 className="text-2xl font-bold text-white mb-4">1. Service Content</h2>
                        <p>
                            Nucleus provides AI-based health management and productivity suggestions. The content output by the application is generated by artificial intelligence algorithms and is for reference purposes only.
                        </p>
                    </div>

                    <div className="p-4 bg-red-500/10 border border-red-500/20 rounded-lg">
                        <h2 className="text-xl font-bold text-red-400 mb-2 mt-0">2. Medical Disclaimer (Important!)</h2>
                        <ul className="list-disc pl-5 space-y-2 text-red-100">
                            <li><strong>No Medical Diagnosis:</strong> Nucleus is NOT a medical device and does not provide medical diagnoses or professional medical advice.</li>
                            <li><strong>Risk Assumption:</strong> Always consult a professional physician before making changes to your exercise habits or lifestyle based on Nucleus's suggestions.</li>
                            <li><strong>Emergencies:</strong> In case of a medical emergency, please contact your local emergency services immediately.</li>
                        </ul>
                    </div>

                    <div>
                        <h2 className="text-2xl font-bold text-white mb-4">3. Limitations of AI</h2>
                        <ul className="list-disc pl-5 space-y-2">
                            <li>User acknowledges that AI may generate inaccurate or outdated information ("AI Hallucination").</li>
                            <li>Users must not use this application to generate any content that is illegal, harmful, or violates others' privacy.</li>
                        </ul>
                    </div>

                    <div>
                        <h2 className="text-2xl font-bold text-white mb-4">4. Subscription & Payments</h2>
                        <ul className="list-disc pl-5 space-y-2">
                            <li>All payments are processed through the Apple App Store.</li>
                            <li>Subscriptions will automatically renew unless turned off at least 24 hours before the end of the current billing cycle.</li>
                        </ul>
                    </div>
                </div>
            </section>

        </div>
    );
};

export default Privacy;
